name: Run tests

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHON_VERSION: '3.10'

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - run: echo "🔎 The job was triggered from repository ${{ github.repository }} and branch ${{ github.ref }}"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout code
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Checkout code
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true


      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      #----------------------------------------------
      # install your root project, and run tests.
      #----------------------------------------------
      - name: Install library and run tests
        run: |
          pip install pytest
          poetry install --no-interaction
          poetry run pytest
